version: '2'

services:
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ~/.docker-volumes/gryphon/elasticsearch/data:/usr/share/elasticsearch/data

  neo4j:
    image: neo4j:3.0.0
    environment:
      NEO4J_AUTH: none
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ~/.docker-volumes/gryphon/neo4j/data:/data

  api:
    build: ./api
    depends_on:
      - neo4j
      - elasticsearch
    links:
      - elasticsearch
      - neo4j
    volumes:
      - ./api:/gryphon_api
    ports:
      - '3000:3000'
    env_file:
      - ./api/api.env
